### ISSUE TITLE
Modifying values in the flights DF 

### ISSUE THREAD

**Issue by Lollo003** [PietroPalo00/WePole#7]
We need to make final modifications to continue with the new features.
In particular we need to:
- Create a function that divides prices by 2 if the value in the "Ticket Single or Return" is labeled as "Return" and generates an additional row right below with the departure and arrival switched (date to be defined)
- Eliminate column "Ticket Single or Return" from original DF

**Comment by PietroPalo00** [comment]
2834fe2c5a32ff0b90f33aaf42cb6f057483bc06
